import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Glass, Tone } from "@/components/ui/Glass";
import { useApp } from "@/lib/store";
import { calcPortfolioReturn } from "@/lib/calc/portfolio-returns";
import { fmtMoney, fmtPctShort, fmtPrice } from "@/lib/format";
import { chinaSessionLabel } from "@/lib/data/market-session";
export const Route=createFileRoute("/tools")({component:ToolsPage});
type Freq="week"|"biweek"|"month";
function xirr(cf:{t:number;v:number}[]){if(cf.length<2)return null;const end=cf.at(-1)!.t;const npv=(r:number)=>cf.reduce((s,c)=>s+c.v/Math.pow(1+r,(c.t-end)/31536000000),0);let lo=-.9999,hi=10;for(let i=0;i<80;i++){const m=(lo+hi)/2,v=npv(m);if(Math.abs(v)<1e-8)return m;if(v>0)lo=m;else hi=m;}return(lo+hi)/2;}
function simulate(points:{date:string;nav:number}[],amount:number,freq:Freq,years:number){const end=points.at(-1);if(!end||amount<=0||years<=0)return null;const start=new Date(end.date+"T00:00:00+08:00").getTime()-years*365.25*86400000;let next=start,shares=0,total=0;const cf:{t:number;v:number}[]=[];for(const p of points){const t=new Date(p.date+"T00:00:00+08:00").getTime();if(t<start||t<next||!Number.isFinite(p.nav)||p.nav<=0)continue;shares+=amount/p.nav;total+=amount;cf.push({t,v:-amount});next=t+(freq==="week"?7:freq==="biweek"?14:30)*86400000;}if(!shares)return null;const terminal=shares*end.nav;cf.push({t:new Date(end.date+"T00:00:00+08:00").getTime(),v:terminal});return{total,terminal,profit:terminal-total,irr:xirr(cf)};}
function ToolsPage(){const portfolio=useApp(s=>s.portfolio),funds=useApp(s=>s.funds);const summary=useMemo(()=>calcPortfolioReturn(portfolio,funds),[funds,portfolio]);const[code,setCode]=useState(portfolio[0]?.code||"");const[amount,setAmount]=useState("500");const[freq,setFreq]=useState<Freq>("month");const[years,setYears]=useState("3");const[shock,setShock]=useState("5");const[target,setTarget]=useState("10");const fund=funds[code];const dca=useMemo(()=>simulate((fund?.historyPoints||[]).map(x=>({date:x.date,nav:x.nav})),Number(amount),freq,Number(years)),[amount,freq,fund?.historyPoints,years]);const stress=summary.marketValue==null?null:summary.marketValue*Number(shock||0)/100;const progress=summary.pricedHoldingPnlPct==null?null:Math.max(0,Math.min(100,summary.pricedHoldingPnlPct/Math.max(.01,Number(target))*100));const session=chinaSessionLabel();return <div className="space-y-3">
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">申赎时机助手</div><div className="mt-0.5 text-[9px] text-muted">{session} · 15:00前提交通常按当日规则确认；实际以基金公告和销售渠道规则为准。</div><div className="mt-2 grid grid-cols-2 gap-2"><select value={code} onChange={e=>setCode(e.target.value)} className="h-10 rounded-xl bg-white/70 px-2 text-[10px] ring-1 ring-white/80">{portfolio.length?portfolio.map(h=><option key={h.code} value={h.code}>{funds[h.code]?.name||h.name}</option>):<option value="">暂无持仓</option>}</select><div className="rounded-xl bg-blue-50/60 px-3 py-2.5 text-[10px]">当前近似净值 <b>{fmtPrice(fund?.estimate??fund?.nav,4)}</b></div></div><div className="mt-2 rounded-xl bg-amber-50/60 p-2.5 text-[9px] text-slate-600">14:30后进入尾盘复核：同时看估值、市场、板块、资金和组合风险；估值不是成交价。</div></Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">定投回测</div><div className="mt-2 grid grid-cols-2 gap-2 text-[9px]"><label>每次金额<input value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80"/></label><label>频率<select value={freq} onChange={e=>setFreq(e.target.value as Freq)} className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80"><option value="week">每周</option><option value="biweek">双周</option><option value="month">每月</option></select></label><label>年限<input value={years} onChange={e=>setYears(e.target.value)} className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80"/></label><label>基金<select value={code} onChange={e=>setCode(e.target.value)} className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80">{portfolio.map(h=><option key={h.code} value={h.code}>{funds[h.code]?.name||h.name}</option>)}</select></label></div>{dca?<div className="mt-2 grid grid-cols-2 gap-1.5"><Metric label="累计投入" value={fmtMoney(dca.total)}/><Metric label="期末市值" value={fmtMoney(dca.terminal)}/><Metric label="累计盈亏" value={fmtMoney(dca.profit)} tone={dca.profit}/><Metric label="XIRR" value={dca.irr==null?"—":fmtPctShort(dca.irr*100)} tone={dca.irr}/></div>:<div className="mt-2 text-[8px] text-muted">需要基金存在足够历史净值；缺数据不补造回测。</div>}<div className="mt-1 text-[8px] text-subtle">按真实净值日期模拟，不等同实际交易费用、分红税费和申赎规则。</div></Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">组合压力测试</div><div className="mt-2 flex gap-2"><input value={shock} onChange={e=>setShock(e.target.value)} className="h-10 min-w-0 flex-1 rounded-xl bg-white/70 px-3 text-[11px]"/><span className="rounded-xl bg-white/70 px-3 py-2.5 text-[10px]">%下跌</span></div><div className="mt-2 rounded-[18px] bg-rose-50/65 p-3"><div className="text-[9px] text-muted">当前持仓市值</div><b className="text-[18px]">{fmtMoney(summary.marketValue)}</b><div className="mt-1 text-[10px] text-rose-600">线性压力亏损约 {stress==null?"—":fmtMoney(-stress)}</div><div className="mt-1 text-[8px] text-muted">可继续自定义 1%–20% 冲击；这是压力场景，不是预测。</div></div></Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">目标收益进度</div><div className="mt-2 flex items-center gap-2"><input value={target} onChange={e=>setTarget(e.target.value)} className="h-10 w-24 rounded-xl bg-white/70 px-3 text-[10px]"/><span className="text-[10px] text-muted">目标持仓收益率 %</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-accent" style={{width:`${progress??0}%`}}/></div><div className="mt-1 flex justify-between text-[9px]"><span>当前 {summary.pricedHoldingPnlPct==null?"—":fmtPctShort(summary.pricedHoldingPnlPct)}</span><b>{progress==null?"—":`${progress.toFixed(0)}%`}</b></div></Glass>
 <Glass className="p-3"><div className="text-[12px] font-semibold">更多工具</div><div className="mt-2 flex flex-wrap gap-2"><Link to="/compare" className="rounded-full bg-white/75 px-3 py-1.5 text-[9px] text-blue-600 ring-1 ring-white/85">五基金对比</Link><Link to="/portfolio" className="rounded-full bg-white/75 px-3 py-1.5 text-[9px] text-blue-600 ring-1 ring-white/85">组合分析</Link></div></Glass>
 </div>}
function Metric({label,value,tone}:{label:string;value:string;tone?:number|null}){return <div className="rounded-xl bg-white/65 p-2"><div className="text-[8px] text-muted">{label}</div><Tone v={tone??null} className="mt-0.5 text-[13px] font-bold">{value}</Tone></div>}