import { useEffect, useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { X, Plus } from "lucide-react";
import { Glass, Tone } from "@/components/ui/Glass";
import { getFund } from "@/lib/data/server";
import { getFundHistory } from "@/lib/data/fund-history";
import { calcHoldingReturn } from "@/lib/calc/portfolio-returns";
import { matchFundSector } from "@/lib/data/sectors";
import { maxDrawdown, sharpeAnnualized, volatilityAnnualized, normalized } from "@/lib/calc/risk-metrics";
import { fmtPctShort, fmtPrice } from "@/lib/format";
import type { FundQuote, FundHistoryPoint, Holding } from "@/lib/types";

const MAX = 5;
type Picked = { code:string; fund:FundQuote };
function metrics(f:FundQuote){const values=f.historyPoints.map(x=>x.nav).filter(x=>Number.isFinite(x)&&x>0);return { oneMonth:values.length>1?(values.at(-1)!/values[Math.max(0,values.length-22)]-1)*100:null, threeMonth:values.length>1?(values.at(-1)!/values[Math.max(0,values.length-66)]-1)*100:null, maxDD:maxDrawdown(values), sharpe:sharpeAnnualized(values), vol:volatilityAnnualized(values)};}
function style(f:FundQuote){const type=/ETF|指数|LOF/i.test(f.type)?"指数/ETF":"主动基金";const concentration=f.disclosedWeight!=null?Math.min(100,Math.round(f.disclosedWeight)):null;const theme=matchFundSector(f.name)?.name||"综合主题";return `${type} · ${theme} · 前十大透明度 ${concentration==null?"待取":`${concentration}%`}`;}
function overlap(a:FundQuote,b:FundQuote){const ah=(a as FundQuote&{liveHoldings?:{code:string;name:string;weight:number}[]}).liveHoldings||[];const bh=(b as FundQuote&{liveHoldings?:{code:string;name:string;weight:number}[]}).liveHoldings||[];if(!ah.length||!bh.length)return null;const am=new Map(ah.map(x=>[x.code,x.weight]));const bm=new Map(bh.map(x=>[x.code,x.weight]));const codes=[...new Set([...am.keys(),...bm.keys()])];return codes.reduce((s,c)=>s+Math.min(am.get(c)||0,bm.get(c)||0),0);}
function curve(values:number[]){const n=normalized(values);if(n.length<2)return null;const w=320,h=90;const min=Math.min(...n),max=Math.max(...n),r=Math.max(.001,max-min);return n.map((v,i)=>`${i?"L":"M"}${(i/(n.length-1))*w},${h-8-((v-min)/r)*(h-16)}`).join(" ");}

export const Route=createFileRoute("/compare")({component:ComparePage});
function ComparePage(){
 const portfolio=useApp(s=>s.portfolio); const funds=useApp(s=>s.funds);
 const [codes,setCodes]=useState<string[]>(()=>portfolio.slice(0,Math.min(5,portfolio.length)).map(h=>h.code));
 const [picked,setPicked]=useState<Picked[]>(()=>codes.map(c=>funds[c]).filter(Boolean).map(f=>({code:f.code,fund:f})));
 const [input,setInput]=useState(""); const [loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;setLoading(true);void Promise.all(codes.map(async c=>{try{return await getFund({data:{code:c}});}catch{return funds[c];}})).then(rows=>{if(live)setPicked(rows.filter((x):x is FundQuote=>!!x&&!!x.code).slice(0,MAX).map(f=>({code:f.code,fund:f})));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[codes]);
 const add=async()=>{const c=input.trim();if(!/^\d{6}$/.test(c)||codes.includes(c)||codes.length>=MAX)return;setInput("");setCodes(v=>[...v,c]);};
 const remove=(c:string)=>setCodes(v=>v.filter(x=>x!==c));
 const holdings=useMemo(()=>picked.map(p=>({code:p.code,name:p.fund.name,shares:1,cost:p.fund.nav||1} as Holding)),[picked]);
 return <div className="space-y-3"><Glass className="rounded-[24px] p-3"><div className="flex items-center justify-between"><div><div className="text-[17px] font-semibold">基金多维对比</div><div className="mt-0.5 text-[9px] text-muted">最多5只 · 收益 / 回撤 / 夏普 / 波动 / 持仓重叠</div></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] text-blue-600">{picked.length}/5</span></div><div className="mt-2 flex gap-1.5 overflow-x-auto">{picked.map(p=><button key={p.code} type="button" onClick={()=>remove(p.code)} className="flex shrink-0 items-center gap-1 rounded-full bg-white/75 px-2.5 py-1.5 text-[9px] ring-1 ring-white/85">{p.fund.name.slice(0,9)}<X size={11}/></button>)}</div><div className="mt-2 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" placeholder="输入基金代码加入对比" className="h-10 min-w-0 flex-1 rounded-xl bg-white/70 px-3 text-[10px] ring-1 ring-white/80 outline-none"/><button type="button" onClick={()=>void add()} disabled={loading||codes.length>=MAX} className="flex h-10 items-center gap-1 rounded-xl bg-slate-900 px-3 text-[10px] font-semibold text-white disabled:opacity-50"><Plus size={13}/>加入</button></div></Glass>
 {picked.length?<><Glass className="overflow-hidden rounded-[24px] p-3"><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-[9px]"><thead><tr className="text-muted"><th className="p-2">指标</th>{picked.map(p=><th key={p.code} className="p-2">{p.fund.name}<div className="font-normal">{p.code}</div></th>)}</tr></thead><tbody>{[["近1月",p=>metrics(p.fund).oneMonth],["近3月",p=>metrics(p.fund).threeMonth],["最大回撤",p=>metrics(p.fund).maxDD],["夏普",p=>metrics(p.fund).sharpe],["年化波动",p=>metrics(p.fund).vol]].map(([label,fn])=><tr key={String(label)} className="border-t border-black/[.04]"><td className="p-2 font-semibold">{label}</td>{picked.map(p=>{const v=(fn as (x:Picked)=>number|null)(p);return <td key={p.code} className="p-2"><Tone v={String(label)==="最大回撤"||String(label)==="年化波动"?-(v||0):v} className="font-semibold">{v==null?"—":String(label)==="夏普"?v.toFixed(2):fmtPctShort(v)}</Tone></td>})}</tr>)}</tbody></table></div></Glass><Glass className="rounded-[24px] p-3"><div className="text-[13px] font-semibold">归一化净值走势</div><div className="mt-2 overflow-x-auto"><svg viewBox="0 0 320 90" className="h-28 min-w-[520px] w-full">{picked.map((p,i)=>{const path=curve(p.fund.historyPoints.map(x=>x.nav));return path?<path key={p.code} d={path} fill="none" stroke="currentColor" strokeWidth="2" className={i%2?"text-slate-400":"text-blue-500"}/>:null})}</svg></div></Glass><Glass className="rounded-[24px] p-3"><div className="text-[13px] font-semibold">持仓重叠与风格画像</div><div className="mt-2 grid gap-1.5">{picked.map((p,i)=><div key={p.code} className="rounded-[16px] bg-white/62 p-2"><div className="text-[10px] font-semibold">{p.fund.name}</div><div className="mt-0.5 text-[8px] text-muted">{style(p.fund)}</div>{picked.filter(q=>q.code!==p.code).map(q=>{const ov=overlap(p.fund,q.fund);return <div key={q.code} className="mt-1 flex items-center justify-between text-[8px]"><span>与 {q.fund.name.slice(0,10)} 重叠</span><b className="text-blue-600">{ov==null?"需取得前十大":`${ov.toFixed(1)}%`}</b></div>})}</div>)}</div><div className="mt-2 text-[8px] leading-relaxed text-subtle">这里的“风格画像”依据公开基金类型、主题映射和持仓透明度，不冒充基金经理专属风格标签。取得公开前十大后可进一步计算股票层重叠。</div></Glass></>:<Glass className="rounded-[24px] p-4 text-center text-[10px] text-muted">先添加2只以上基金即可比较。你也可以输入任意6位基金代码。</Glass>}
 <Glass className="rounded-[24px] p-3"><div className="text-[10px] text-muted">关联工具</div><Link to="/tools" className="mt-1 inline-block text-[11px] font-semibold text-blue-600">去定投 / 压力测试 / 申赎时机 ›</Link></Glass>
 </div>;
}
