import type { FundQuote, SectorQuote } from "./types";
export type AlertKind="fund_up"|"fund_down"|"drawdown"|"valuation_range"|"sector_change"|"three_down";
export type AlertRule={id:string;code:string;kind:AlertKind;threshold:number;enabled:boolean};
export type AlertEvent={id:string;ruleId:string;code:string;kind:AlertKind;value:number;threshold:number;message:string;triggeredAt:number};
const RULE_KEY="fund_ai_pro_alert_rules_v1",EVENT_KEY="fund_ai_pro_alert_events_v1",SECTOR_KEY="fund_ai_pro_alert_sector_snapshot_v1",ESTIMATE_KEY="fund_ai_pro_estimate_close_v1",OFFICIAL_KEY="fund_ai_pro_official_notice_v1",COOLDOWN_MS=60*60_000;
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback;}catch{return fallback;}}
function write(key:string,value:unknown){if(typeof window!=="undefined")try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
export function loadAlertRules():AlertRule[]{return read<AlertRule[]>(RULE_KEY,[]).filter(r=>r&&typeof r.id==="string"&&typeof r.code==="string"&&Number.isFinite(Number(r.threshold))&&["fund_up","fund_down","drawdown","valuation_range","sector_change","three_down"].includes(r.kind));}
export function saveAlertRules(rules:AlertRule[]){write(RULE_KEY,rules);}export function loadAlertEvents():AlertEvent[]{return read<AlertEvent[]>(EVENT_KEY,[]).filter(e=>e&&typeof e.id==="string").slice(0,50);}
export function notifyAlertEvents(events:AlertEvent[]){if(typeof window==="undefined"||!events.length||typeof Notification==="undefined"||Notification.permission!=="granted")return;for(const e of events.slice(0,3)){try{new Notification("Fund AI Pro · 智能提醒",{body:e.message,tag:`fap-alert-${e.ruleId}`});}catch{}}}
function maxDrawdown(history:number[]){let peak=-Infinity,max=0;for(const v of history){if(!Number.isFinite(v)||v<=0)continue;peak=Math.max(peak,v);if(peak>0)max=Math.max(max,(peak-v)/peak*100);}return max;}
function threeDown(q:FundQuote){const changes=q.historyPoints.slice().reverse().map(p=>p.changePct).filter((v):v is number=>v!=null&&Number.isFinite(v)).slice(0,3);return changes.length===3&&changes.every(v=>v<0)?3:null;}
function matches(rule:AlertRule,q:FundQuote){const day=q.dayPct;if(rule.kind==="fund_up")return day!=null&&day>=rule.threshold?day:null;if(rule.kind==="fund_down")return day!=null&&day<=-Math.abs(rule.threshold)?day:null;if(rule.kind==="drawdown"){const dd=maxDrawdown(q.history||[]);return dd>=Math.abs(rule.threshold)?dd:null;}if(rule.kind==="three_down")return threeDown(q);const low=q.estimateRangeLowPct,high=q.estimateRangeHighPct,t=Math.abs(rule.threshold);if(low!=null&&low<=-t)return low;if(high!=null&&high>=t)return high;return q.estimatePct!=null&&Math.abs(q.estimatePct)>=t?q.estimatePct:null;}
function message(rule:AlertRule,q:FundQuote,v:number){if(rule.kind==="fund_up")return `${q.name||rule.code} 今日涨幅 ${v.toFixed(2)}% ≥ +${rule.threshold.toFixed(2)}%`;if(rule.kind==="fund_down")return `${q.name||rule.code} 今日跌幅 ${v.toFixed(2)}% ≤ -${Math.abs(rule.threshold).toFixed(2)}%`;if(rule.kind==="drawdown")return `${q.name||rule.code} 历史最大回撤 ${v.toFixed(2)}% ≥ ${Math.abs(rule.threshold).toFixed(2)}%`;if(rule.kind==="three_down")return `${q.name||rule.code} 最近3个可靠净值日连续下跌，触发观察提醒`;return `${q.name||rule.code} 盘中估值区间已触及 ${v.toFixed(2)}%（阈值 ±${Math.abs(rule.threshold).toFixed(2)}%）`;}
function sectorEvent(rule:AlertRule,sectors:SectorQuote[],previous:Record<string,number>):AlertEvent|null{const code=rule.code.replace(/^sector:/,"");const s=sectors.find(x=>x.bkCode===code||x.id===code);if(!s||s.change==null)return null;const before=previous[code];previous[code]=s.change;if(before==null)return null;const d=s.change-before;return Math.abs(d)>=Math.abs(rule.threshold)?{id:`${rule.id}-${Date.now()}`,ruleId:rule.id,code:rule.code,kind:rule.kind,value:d,threshold:rule.threshold,message:`${s.name} 强弱变化 ${d>=0?"+":""}${d.toFixed(2)} 个百分点`,triggeredAt:Date.now()}:null;}
function automaticOfficial(funds:Record<string,FundQuote>,events:AlertEvent[],now:number){const out:AlertEvent[]=[];if(!Object.keys(funds).length)return out;const saved=read<Record<string,string>>(OFFICIAL_KEY,{});const estimates=read<Record<string,{ts:number;fundNav?:number}>>(ESTIMATE_KEY,{});for(const q of Object.values(funds)){if(!q.officialNavPublished||!q.navDate||q.nav==null)continue;const key=`${q.code}:${q.navDate}`;if(saved[q.code]===q.navDate)continue;const recent=events.find(e=>e.ruleId===`auto-official-${q.code}`&&now-e.triggeredAt<COOLDOWN_MS);if(recent)continue;out.push({id:`auto-official-${q.code}-${q.navDate}`,ruleId:`auto-official-${q.code}`,code:q.code,kind:"fund_up",value:q.dayPct??0,threshold:0,message:`${q.name||q.code} 今日官方净值已确认：${q.nav.toFixed(4)}，今日${q.dayPct==null?"涨跌待核对":`涨跌 ${q.dayPct.toFixed(2)}%`}`,triggeredAt:now,});saved[q.code]=q.navDate;const e=estimates[q.code];if(e?.fundNav!=null&&e.ts>0){const deviation=(e.fundNav-q.nav)/q.nav*100;if(Math.abs(deviation)>=1)out.push({id:`auto-deviation-${q.code}-${q.navDate}`,ruleId:`auto-deviation-${q.code}`,code:q.code,kind:"valuation_range",value:deviation,threshold:1,message:`${q.name||q.code} 收盘估算与官方净值偏差 ${deviation>=0?"+":""}${deviation.toFixed(2)}%，超过1%观察线`,triggeredAt:now});}}
write(OFFICIAL_KEY,saved);return out;}
export function evaluateFundAlerts(funds:Record<string,FundQuote>,sectors:SectorQuote[]=[]){if(typeof window==="undefined")return[];const rules=loadAlertRules().filter(r=>r.enabled),events=loadAlertEvents(),now=Date.now(),created:AlertEvent[]=[],previous=read<Record<string,number>>(SECTOR_KEY,{});for(const rule of rules){if(rule.kind==="sector_change"){const e=sectorEvent(rule,sectors,previous);if(e&&!events.some(x=>x.ruleId===rule.id&&now-x.triggeredAt<COOLDOWN_MS))created.push(e);continue;}if(!/^\d{6}$/.test(rule.code))continue;const q=funds[rule.code];if(!q)continue;const v=matches(rule,q);if(v==null||events.some(e=>e.ruleId===rule.id&&now-e.triggeredAt<COOLDOWN_MS))continue;created.push({id:`${rule.id}-${now}`,ruleId:rule.id,code:rule.code,kind:rule.kind,value:v,threshold:rule.threshold,message:message(rule,q,v),triggeredAt:now});}created.push(...automaticOfficial(funds,events,now));if(sectors.length)write(SECTOR_KEY,previous);if(created.length)write(EVENT_KEY,[...created,...events].slice(0,50));return created;}
export const alertKindLabel:Record<AlertKind,string>={fund_up:"涨幅提醒",fund_down:"跌幅提醒",drawdown:"回撤提醒",valuation_range:"估值区间",sector_change:"板块变化",three_down:"连续3日下跌"};
export const DEFAULT_ALERT_RULES=(codes:string[]):AlertRule[]=>codes.flatMap(code=>[{id:`${code}-up3`,code,kind:"fund_up" as const,threshold:3,enabled:true},{id:`${code}-down3`,code,kind:"fund_down" as const,threshold:3,enabled:true},{id:`${code}-3down`,code,kind:"three_down" as const,threshold:3,enabled:true}]);
