import { createServerFn } from "@tanstack/react-start";
import { fetchText, n, parseMaybeJsonp, asArr } from "./fetch-util";

type MacroOverview = { bond10y:number|null; bondDate:string|null; bondChangeBp:number|null; northbound:number|null; northboundDate:string|null; csi300Pe:number|null; earningsYield:number|null; stockBondSpread:number|null; source:string };
const UT="fa5fd1943c7b386f172d6893dbfba10b";
function findNumber(value:unknown, keys:string[]):number|null{if(value==null)return null;if(Array.isArray(value)){for(const x of value){const h=findNumber(x,keys);if(h!=null)return h;}return null;}if(typeof value!=="object")return null;const o=value as Record<string,unknown>;for(const k of keys){const v=n(o[k]);if(v!=null)return v;}for(const v of Object.values(o)){const h=findNumber(v,keys);if(h!=null)return h;}return null;}
function findDate(value:unknown):string|null{if(value==null)return null;if(Array.isArray(value)){for(const x of value){const h=findDate(x);if(h)return h;}return null;}if(typeof value!=="object")return null;const o=value as Record<string,unknown>;for(const k of ["date","trade_date","datetime","update_time","f51"]){const v=String(o[k]??"");if(/^20\d{2}[-/]\d{2}[-/]\d{2}/.test(v))return v.slice(0,10);}for(const v of Object.values(o)){const h=findDate(v);if(h)return h;}return null;}
async function bond(){try{const raw=await fetchText("https://api-ddc-wscn.awtmt.com/market/real?fields=symbol,prod_name,last_px,px_change,px_change_rate,update_time&prod_code=CN10YR.OTC",7000);const j=parseMaybeJsonp(raw);const obj=j&&typeof j==="object"?(j as any)?.data?.snapshot?.["CN10YR.OTC"]??(j as any)?.data?.snapshot??j:null;const arr=Array.isArray(obj)?obj:Object.values(obj||{});const row=Array.isArray(obj)?obj:arr.find((x:any)=>x&&typeof x==="object");const value=n(Array.isArray(row)?row[2]:row?.last_px);const ch=n(Array.isArray(row)?row[3]:row?.px_change);return {value,changeBp:ch!=null?ch*100:null,date:findDate(j)};}catch{return {value:null,changeBp:null,date:null};}}
async function northbound(){try{const raw=await fetchText(`https://push2.eastmoney.com/api/qt/kamt.kline/get?klt=101&fields1=f1,f2,f3,f4&fields2=f51,f52,f53,f54,f55,f56&lmt=1&ut=${UT}&_=${Date.now()}`,7000,{Referer:"https://data.eastmoney.com/"});const j=parseMaybeJsonp(raw) as any;const data=j?.data??j;let total=null,date=null;const candidates:[string,string[]][]=[["sh2hk",["sh2hk","s2hk","shhk"]],["sz2hk",["sz2hk","s2sz","szhk"]]];const readSeries=(v:any)=>{if(Array.isArray(v?.klines))return v.klines;if(Array.isArray(v))return v;return []};for(const [,keys] of candidates){let found:any=null;for(const k of keys){if(data?.[k]){found=data[k];break;}}if(!found)continue;const rows=readSeries(found);const line=rows.at(-1);if(!line)continue;const p=String(line).split(",");const v=n(p.at(-1));if(v!=null)total=(total??0)+v;date=date??(p[0]?.slice(0,10)||null);}if(total!=null)return {value:total,date};const lines=readSeries(data);const line=lines.at(-1);if(line){const p=String(line).split(",");return {value:n(p.at(-1)),date:p[0]?.slice(0,10)||null};}return {value:null,date:null};}catch{return {value:null,date:null};}}
async function csi300Pe(){try{const raw=await fetchText("https://push2.eastmoney.com/api/qt/stock/get?secid=1.000300&fields=f57,f58,f162,f167&_="+Date.now(),6000,{Referer:"https://quote.eastmoney.com/"});const j=JSON.parse(raw) as any;const peRaw=n(j?.data?.f162);return peRaw==null?null:peRaw/100;}catch{return null;}}
export const getChinaMacroOverview=createServerFn({method:"GET"}).handler(async():Promise<MacroOverview>=>{const [b,north,pe]=await Promise.all([bond(),northbound(),csi300Pe()]);const earningsYield=pe!=null&&pe>0?100/pe:null;const spread=earningsYield!=null&&b.value!=null?earningsYield-b.value:null;return{bond10y:b.value,bondDate:b.date,bondChangeBp:b.changeBp,northbound:north.value,northboundDate:north.date,csi300Pe:pe,earningsYield,stockBondSpread:spread,source:"华尔街见闻/东方财富公开行情接口"};});
