import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Glass, Tone } from "@/components/ui/Glass";
import { useApp } from "@/lib/store";
import { getFundHistory } from "@/lib/data/fund-history";
import { getMarketPhase } from "@/lib/market-hours";
import { cnTime, fmtMoney, fmtPctShort, fmtPrice } from "@/lib/format";
import { calcPortfolioReturn } from "@/lib/calc/portfolio-returns";
import type { FundQuote } from "@/lib/types";

function xirr(cashflows:{date:Date;value:number}[]){if(cashflows.length<2)return null;const end=cashflows[cashflows.length-1].date.getTime();const npv=(rate:number)=>cashflows.reduce((s,c)=>s+c.value/Math.pow(1+rate,(c.date.getTime()-end)/31536000000),0);let lo=-0.999,hi=10;for(let i=0;i<80;i++){const mid=(lo+hi)/2;const v=npv(mid);if(Math.abs(v)<1e-7)return mid;if(v>0)lo=mid;else hi=mid;}return (lo+hi)/2;}
function simulateDca(points:{date:string;nav:number}[], amount:number, frequency:"week"|"biweek"|"month", years:number){const end=points.at(-1);if(!end)return null;const startMs=new Date(end.date+"T00:00:00+08:00").getTime()-years*365.25*86400000;let next=startMs;let shares=0,total=0;const flows:{date:Date;value:number}[]=[];for(const p of points){const t=new Date(p.date+"T00:00:00+08:00").getTime();if(t<startMs)continue;if(t<next)continue;shares+=amount/p.nav;total+=amount;flows.push({date:new Date(t),value:-amount});const step=frequency==="week"?7:frequency==="biweek"?14:30;next=t+step*86400000;}if(!shares)return null;const terminal=shares*end.nav;flows.push({date:new Date(end.date+"T00:00:00+08:00"),value:terminal});return {total,shares,terminal,profit:terminal-total,irr:xirr(flows)};}
function selectedFundCode(portfolio: {code:string}[], fundMap:Record<string,FundQuote>){return portfolio.find(x=>fundMap[x.code])?.code||portfolio[0]?.code||"";}

export const Route=createFileRoute("/tools")({component:ToolsPage});
function ToolsPage(){
 const portfolio=useApp(s=>s.portfolio);const funds=useApp(s=>s.funds);const [code,setCode]=useState(()=>selectedFundCode(portfolio,funds));const [amount,setAmount]=useState("500");const [frequency,setFrequency]=useState<"week"|"biweek"|"month">("month");const [years,setYears]=useState("3");const [history,setHistory]=useState<{date:string;nav:number}[]>([]);const [loading,setLoading]=useState(false);const [stress,setStress]=useState("5");const [target,setTarget]=useState("10");
 const fund=funds[code];const summary=useMemo(()=>calcPortfolioReturn(portfolio,funds),[portfolio,funds]);const phase=getMarketPhase();const cn=cnTime();const minutes=cn.getUTCHours()*60+cn.getUTCMinutes();const beforeClose=minutes<15*60;const canRedeemToday=beforeClose&&phase!=="closed";const approxPrice=fund?.estimate??fund?.nav??null;const timing=phase==="morning"||phase==="lunch"||phase==="afternoon"?`现在处于${phase==="morning"?"上午交易":phase==="lunch"?"午间休市":"下午交易"}，15:00前提交通常按今日净值确认规则执行。`:"当前非A股交易时段，下一交易日规则为准。";
 const dca=useMemo(()=>{if(!history.length)return null;return simulateDca(history,Number(amount)||0,frequency,Number(years)||0);},[amount,frequency,history,years]);
 const stressAmt=summary.marketValue!=null?(summary.marketValue*(Number(stress)||0)/100):null;const targetProgress=summary.pricedHoldingPnlPct==null?null:Math.max(0,Math.min(100,summary.pricedHoldingPnlPct/Math.max(0.01,Number(target))*100));
 const loadHistory=async()=>{if(!/^\d{6}$/.test(code))return;setLoading(true);try{const rows=await getFundHistory({data:{code,pageSize:2500}});setHistory(rows.map(x=>({date:x.date,nav:x.nav??0})));}finally{setLoading(false);}};
 return <div className="space-y-3"><Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">申赎时机助手</div><div className="mt-1 text-[9px] text-muted">15:00截止 · 估值仅作近似价格参考，不代表实际成交价</div><div className="mt-2 rounded-[18px] bg-blue-50/55 p-3"><div className="text-[12px] font-semibold text-blue-700">{timing}</div><div className="mt-1 grid grid-cols-2 gap-2 text-[9px]"><div>选择基金 <select value={code} onChange={e=>setCode(e.target.value)} className="mt-1 h-9 w-full rounded-xl bg-white px-2 ring-1 ring-white/80">{portfolio.length?portfolio.map(h=><option key={h.code} value={h.code}>{funds[h.code]?.name||h.name}</option>):<option value="">暂无持仓</option>}</select></div><div>当前近似价<div className="mt-1 h-9 rounded-xl bg-white px-2 py-2 font-semibold">{fmtPrice(approxPrice,4)}</div></div></div><div className="mt-2 text-[8px] text-muted">临近14:30建议进入尾盘复核窗口：看估值、板块、资金与风险，再决定是否提交。官方净值发布后以官方值替代估值。</div></div></Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">定投计算器 + 历史回测</div><div className="mt-2 grid grid-cols-2 gap-2 text-[9px]"><label>每次金额<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80"/></label><label>周期<select value={frequency} onChange={e=>setFrequency(e.target.value as any)} className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80"><option value="week">每周</option><option value="biweek">双周</option><option value="month">每月</option></select></label><label>回测年限<input value={years} onChange={e=>setYears(e.target.value)} inputMode="numeric" className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80"/></label><label>基金<select value={code} onChange={e=>setCode(e.target.value)} className="mt-1 h-9 w-full rounded-xl bg-white/70 px-2 ring-1 ring-white/80">{portfolio.map(h=><option key={h.code} value={h.code}>{funds[h.code]?.name||h.name}</option>)}</select></label></div><button type="button" onClick={()=>void loadHistory()} className="mt-2 h-9 w-full rounded-xl bg-slate-900 text-[10px] font-semibold text-white">{loading?"正在读取历史净值…":"读取最长可用历史并回测"}</button>{dca?<div className="mt-2 grid grid-cols-2 gap-1.5"><Metric label="累计投入" value={fmtMoney(dca.total)}/><Metric label="期末市值" value={fmtMoney(dca.terminal)}/><Metric label="累计盈亏" value={fmtMoney(dca.profit)} tone={dca.profit}/><Metric label="内部收益率" value={dca.irr==null?"—":fmtPctShort(dca.irr*100)} tone={dca.irr??null}/></div>:<div className="mt-2 text-[8px] text-muted">读取历史后按真实净值日做定投模拟；历史不足时不补造收益率。</div>}</Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">组合压力测试</div><div className="mt-1 text-[9px] text-muted">假设下一交易日整体下跌，自定义冲击幅度</div><div className="mt-2 flex gap-2"><input value={stress} onChange={e=>setStress(e.target.value)} inputMode="decimal" className="h-10 min-w-0 flex-1 rounded-xl bg-white/70 px-3 text-[11px]"/><span className="rounded-xl bg-white/70 px-3 py-2.5 text-[10px]">%</span></div><div className="mt-2 rounded-[18px] bg-rose-50/65 p-3"><div className="text-[9px] text-muted">当前持仓市值</div><b className="text-[18px]">{fmtMoney(summary.marketValue)}</b><div className="mt-1 text-[9px] text-rose-600">理论冲击亏损 {stressAmt==null?"—":fmtMoney(-stressAmt)}</div><div className="mt-1 text-[8px] text-slate-500">这是线性压力测试，不模拟基金经理应对、行业非同步下跌或赎回限制。</div></div></Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[17px] font-semibold">目标收益进度</div><div className="mt-2 flex gap-2"><input value={target} onChange={e=>setTarget(e.target.value)} inputMode="decimal" className="h-10 w-28 rounded-xl bg-white/70 px-3 text-[10px]"/><span className="py-3 text-[10px]">目标持有收益率 %</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-accent" style={{width:`${targetProgress??0}%`}}/></div><div className="mt-1 flex items-center justify-between text-[9px]"><span>当前 {summary.pricedHoldingPnlPct==null?"—":fmtPctShort(summary.pricedHoldingPnlPct)}</span><b>{targetProgress==null?"—":`${targetProgress.toFixed(0)}%`}</b></div><div className="mt-2 text-[8px] text-muted">进度只反映当前已计价持仓，不代表未来收益概率。</div></Glass>
 <Glass className="rounded-[24px] p-3"><div className="text-[12px] font-semibold">关联页面</div><div className="mt-1 flex flex-wrap gap-2"><Link to="/compare" className="rounded-full bg-white/75 px-3 py-1.5 text-[9px] text-blue-600 ring-1 ring-white/85">五基金对比</Link><Link to="/ai" className="rounded-full bg-white/75 px-3 py-1.5 text-[9px] text-blue-600 ring-1 ring-white/85">证据链</Link><Link to="/portfolio" className="rounded-full bg-white/75 px-3 py-1.5 text-[9px] text-blue-600 ring-1 ring-white/85">我的持仓</Link></div></Glass></div>;
}
function Metric({label,value,tone}:{label:string;value:string;tone?:number|null}){return <div className="rounded-xl bg-white/65 p-2"><div className="text-[8px] text-muted">{label}</div><Tone v={tone??null} className="mt-0.5 text-[13px] font-bold">{value}</Tone></div>}
