import type { FundQuote, SectorQuote } from "./types";

export type AlertKind = "fund_up" | "fund_down" | "drawdown" | "valuation_range" | "sector_change" | "three_down";
export type AlertRule = { id:string; code:string; kind:AlertKind; threshold:number; enabled:boolean };
export type AlertEvent = { id:string; ruleId:string; code:string; kind:AlertKind; value:number; threshold:number; message:string; triggeredAt:number };
const RULE_KEY="fund_ai_pro_alert_rules_v1", EVENT_KEY="fund_ai_pro_alert_events_v1", SECTOR_KEY="fund_ai_pro_alert_sector_snapshot_v1", COOLDOWN_MS=60*60_000;
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback;}catch{return fallback;}}
function write(key:string,value:unknown){if(typeof window!=="undefined")try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
export function loadAlertRules():AlertRule[]{return read<AlertRule[]>(RULE_KEY,[]).filter(r=>r&&typeof r.id==="string"&&typeof r.code==="string"&&Number.isFinite(Number(r.threshold))&&["fund_up","fund_down","drawdown","valuation_range","sector_change","three_down"].includes(r.kind));}
export function saveAlertRules(rules:AlertRule[]){write(RULE_KEY,rules);}
export function loadAlertEvents():AlertEvent[]{return read<AlertEvent[]>(EVENT_KEY,[]).filter(e=>e&&typeof e.id==="string").slice(0,50);}
export function notifyAlertEvents(events:AlertEvent[]){if(typeof window==="undefined"||!events.length||typeof Notification==="undefined"||Notification.permission!=="granted")return;for(const e of events.slice(0,3)){try{new Notification("Fund AI Pro · 智能提醒",{body:e.message,tag:`fap-alert-${e.ruleId}`});}catch{}}}
function maxDrawdown(history:number[]){let peak=-Infinity,max=0;for(const v of history){if(!Number.isFinite(v)||v<=0)continue;peak=Math.max(peak,v);if(peak>0)max=Math.max(max,(peak-v)/peak*100);}return max;}
function threeDown(quote:FundQuote){const points=(quote.historyPoints||[]).slice().reverse();const changes:number[]=[];for(const p of points){if(p.changePct!=null&&Number.isFinite(p.changePct))changes.push(p.changePct);if(changes.length>=3)break;}return changes.length>=3&&changes.every(v=>v<0)?3:null;}
function matchesFund(rule:AlertRule,quote:FundQuote){const day=quote.dayPct;if(rule.kind==="fund_up")return day!=null&&day>=rule.threshold?day:null;if(rule.kind==="fund_down")return day!=null&&day<=-Math.abs(rule.threshold)?day:null;if(rule.kind==="drawdown"){const dd=maxDrawdown(quote.history||[]);return dd>=Math.abs(rule.threshold)?dd:null;}if(rule.kind==="three_down")return threeDown(quote);const low=quote.estimateRangeLowPct,high=quote.estimateRangeHighPct,target=Math.abs(rule.threshold);if(low!=null&&low<=-target)return low;if(high!=null&&high>=target)return high;const estimate=quote.estimatePct;return estimate!=null&&Math.abs(estimate)>=target?estimate:null;}
function message(rule:AlertRule,quote:FundQuote,value:number){if(rule.kind==="fund_up")return `${quote.name||rule.code} 今日涨幅 ${value.toFixed(2)}% ≥ +${rule.threshold.toFixed(2)}%`;if(rule.kind==="fund_down")return `${quote.name||rule.code} 今日跌幅 ${value.toFixed(2)}% ≤ -${Math.abs(rule.threshold).toFixed(2)}%`;if(rule.kind==="drawdown")return `${quote.name||rule.code} 历史最大回撤 ${value.toFixed(2)}% ≥ ${Math.abs(rule.threshold).toFixed(2)}%`;if(rule.kind==="three_down")return `${quote.name||rule.code} 最近3个可靠净值日连续下跌，触发观察提醒`;return `${quote.name||rule.code} 盘中估值区间已触及 ${value.toFixed(2)}%（阈值 ±${Math.abs(rule.threshold).toFixed(2)}%）`;}
function evaluateSectorRule(rule:AlertRule,sectors:SectorQuote[],previous:Record<string,number>):AlertEvent|null{const code=rule.code.replace(/^sector:/,"");const sector=sectors.find(x=>x.bkCode===code||x.id===code);if(!sector||sector.change==null||!Number.isFinite(sector.change))return null;const before=previous[code];previous[code]=sector.change;if(before==null)return null;const delta=sector.change-before;return Math.abs(delta)>=Math.abs(rule.threshold)?{id:`${rule.id}-${Date.now()}`,ruleId:rule.id,code:rule.code,kind:rule.kind,value:delta,threshold:rule.threshold,message:`${sector.name} 强弱变化 ${delta>=0?"+":""}${delta.toFixed(2)} 个百分点，已达到 ±${Math.abs(rule.threshold).toFixed(2)} 阈值`,triggeredAt:Date.now()}:null;}
export function evaluateFundAlerts(funds:Record<string,FundQuote>,sectors:SectorQuote[]=[]){if(typeof window==="undefined")return[];const rules=loadAlertRules().filter(r=>r.enabled),events=loadAlertEvents(),now=Date.now(),created:AlertEvent[]=[],previous=read<Record<string,number>>(SECTOR_KEY,{});for(const rule of rules){if(rule.kind==="sector_change"){const e=evaluateSectorRule(rule,sectors,previous);if(e&&!events.some(x=>x.ruleId===rule.id&&now-x.triggeredAt<COOLDOWN_MS))created.push(e);continue;}if(!/^\d{6}$/.test(rule.code))continue;const quote=funds[rule.code];if(!quote)continue;const value=matchesFund(rule,quote);if(value==null||events.some(e=>e.ruleId===rule.id&&now-e.triggeredAt<COOLDOWN_MS))continue;created.push({id:`${rule.id}-${now}`,ruleId:rule.id,code:rule.code,kind:rule.kind,value,threshold:rule.threshold,message:message(rule,quote,value),triggeredAt:now});}if(sectors.length)write(SECTOR_KEY,previous);if(created.length)write(EVENT_KEY,[...created,...events].slice(0,50));return created;}
export const alertKindLabel:Record<AlertKind,string>={fund_up:"涨幅提醒",fund_down:"跌幅提醒",drawdown:"回撤提醒",valuation_range:"估值区间",sector_change:"板块变化",three_down:"连续3日下跌"};
export const DEFAULT_ALERT_RULES=(codes:string[]):AlertRule[]=>codes.flatMap(code=>[{id:`${code}-up3`,code,kind:"fund_up" as const,threshold:3,enabled:true},{id:`${code}-down3`,code,kind:"fund_down" as const,threshold:3,enabled:true},{id:`${code}-3down`,code,kind:"three_down" as const,threshold:3,enabled:true}]);
