import { createECDH, createPrivateKey, createSign, randomBytes, createCipheriv, createHmac } from "node:crypto";

type PushSubscription = { endpoint:string; keys:{p256dh:string;auth:string}; expirationTime?:number|null };
function b64urlToBuf(value:string){const s=value.replace(/-/g,"+").replace(/_/g,"/");return Buffer.from(s+"=".repeat((4-s.length%4)%4),"base64");}
function bufToB64url(value:Buffer){return value.toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function hmac(key:Buffer,data:Buffer){return createHmac("sha256",key).update(data).digest();}
function hkdfExtract(salt:Buffer,ikm:Buffer){return hmac(salt,ikm);}
function hkdfExpand(prk:Buffer,info:Buffer,length:number){let t=Buffer.alloc(0),out=Buffer.alloc(0);for(let i=1;out.length<length;i+=1){t=hmac(prk,Buffer.concat([t,info,Buffer.from([i])]));out=Buffer.concat([out,t]);}return out.subarray(0,length);}
function vapidKeys(){const privateRaw=b64urlToBuf(String(process.env.VAPID_PRIVATE_KEY||""));if(privateRaw.length!==32)throw new Error("VAPID_PRIVATE_KEY must be a 32-byte base64url key");const ecdh=createECDH("prime256v1");ecdh.setPrivateKey(privateRaw);const publicRaw=String(process.env.VAPID_PUBLIC_KEY||"")?b64urlToBuf(String(process.env.VAPID_PUBLIC_KEY)):ecdh.getPublicKey();if(publicRaw.length!==65||publicRaw[0]!==4)throw new Error("VAPID_PUBLIC_KEY must be an uncompressed P-256 public key");return {privateRaw,publicRaw};}
function vapidJwt(endpoint:string){const {privateRaw,publicRaw}=vapidKeys();const url=new URL(endpoint);const audience=`${url.protocol}//${url.host}`;const header=bufToB64url(Buffer.from(JSON.stringify({typ:"JWT",alg:"ES256"})));const payload=bufToB64url(Buffer.from(JSON.stringify({aud:audience,exp:Math.floor(Date.now()/1000)+12*60*60,sub:String(process.env.VAPID_SUBJECT||"mailto:admin@example.com")})));const data=`${header}.${payload}`;const ec=createECDH("prime256v1");ec.setPrivateKey(privateRaw);const publicPoint=ec.getPublicKey();const der=Buffer.concat([Buffer.from("302e0201010420","hex"),privateRaw,Buffer.from("a00706052b8104000aa144034200","hex"),publicPoint]);const key=createPrivateKey({key:der,format:"der",type:"pkcs8"});const sign=createSign("sha256");sign.update(data);sign.end();const signature=sign.sign({key,dsaEncoding:"ieee-p1363"});return `vapid t=${data}.${bufToB64url(signature)}, k=${bufToB64url(publicRaw)}`;}
function encryptPayload(subscription:PushSubscription,payload:string){const clientPublic=b64urlToBuf(subscription.keys.p256dh);const auth=b64urlToBuf(subscription.keys.auth);if(clientPublic.length!==65||clientPublic[0]!==4)throw new Error("invalid-p256dh");if(auth.length!==16)throw new Error("invalid-auth");const ecdh=createECDH("prime256v1");ecdh.generateKeys();const serverPublic=ecdh.getPublicKey();const shared=ecdh.computeSecret(clientPublic);const authInfo=Buffer.concat([Buffer.from("WebPush: info\0","utf8"),clientPublic,serverPublic]);const ikm=hkdfExpand(hkdfExtract(auth,shared),authInfo,32);const salt=randomBytes(16);const prk=hkdfExtract(salt,ikm);const cek=hkdfExpand(prk,Buffer.from("Content-Encoding: aes128gcm\0","utf8"),16);const nonce=hkdfExpand(prk,Buffer.from("Content-Encoding: nonce\0","utf8"),12);const padded=Buffer.concat([Buffer.from(payload,"utf8"),Buffer.from([2])]);const cipher=createCipheriv("aes-128-gcm",cek,nonce);const ciphertext=Buffer.concat([cipher.update(padded),cipher.final(),cipher.getAuthTag()]);const recordSize=4096;const rs=Buffer.alloc(4);rs.writeUInt32BE(recordSize,0);const body=Buffer.concat([salt,rs,Buffer.from([serverPublic.length]),serverPublic,ciphertext]);return body;}
export async function sendWebPush(subscription:PushSubscription,payload:unknown){const body=encryptPayload(subscription,JSON.stringify(payload));const response=await fetch(subscription.endpoint,{method:"POST",headers:{Authorization:vapidJwt(subscription.endpoint),TTL:"300",Urgency:"normal",Topic:"fund-ai-pro",Content-Encoding:"aes128gcm",Content-Type:"application/octet-stream"},body});if(!response.ok){const error=new Error(`push-service-${response.status}`);(error as Error&{status?:number}).status=response.status;throw error;}return true;}
