/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as BandRouteImport } from './routes/band'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BandRoute = BandRouteImport.update({
  id: '/band',
  path: '/band',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/band': typeof BandRoute
  '/funds': typeof FundsRoute
  '/market': typeof MarketRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/band': typeof BandRoute
  '/funds': typeof FundsRoute
  '/market': typeof MarketRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/band': typeof BandRoute
  '/funds': typeof FundsRoute
  '/market': typeof MarketRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/band'
    | '/funds'
    | '/market'
    | '/more'
    | '/news'
    | '/portfolio'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/band'
    | '/funds'
    | '/market'
    | '/more'
    | '/news'
    | '/portfolio'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/band'
    | '/funds'
    | '/market'
    | '/more'
    | '/news'
    | '/portfolio'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BandRoute: typeof BandRoute
  FundsRoute: typeof FundsRoute
  MarketRoute: typeof MarketRoute
  MoreRoute: typeof MoreRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band': {
      id: '/band'
      path: '/band'
      fullPath: '/band'
      preLoaderRoute: typeof BandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BandRoute: BandRoute,
  FundsRoute: FundsRoute,
  MarketRoute: MarketRoute,
  MoreRoute: MoreRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
