import { useState, type ReactNode } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";
import { IndexGrid } from "@/components/market/IndexGrid";
import { ExtendedIndexMatrix } from "@/components/market/ExtendedIndexMatrix";
import { IndexValuationLights } from "@/components/market/IndexValuationLights";
import { MarketHeatmap } from "@/components/market/MarketHeatmap";
import { MarketPanorama } from "@/components/market/MarketPanorama";
import { MacroOverview } from "@/components/market/MacroOverview";
import { FundSectorWatchV2 } from "@/components/fund-sector/FundSectorWatchV2";
import { OperationAdvice } from "@/components/market/OperationAdvice";
import { EmptyNote, Tone } from "@/components/ui/Glass";
import { fmtPctShort } from "@/lib/format";
import { useApp } from "@/lib/store";
import { getSnapshot } from "@/lib/data/server";
import { getLatestTradingMarketData } from "@/lib/data/market-fallback";
import { getGlobalMarketFallback } from "@/lib/data/global-market-fallback";
import type { Snapshot } from "@/lib/types";

export const Route = createFileRoute("/market")({ loader: async()=>{const [a,b,c]=await Promise.allSettled([getSnapshot(),getLatestTradingMarketData(),getGlobalMarketFallback()]);const snapshot=a.status==="fulfilled"?a.value:null;const fallback=b.status==="fulfilled"?b.value:null;const globalFallback=c.status==="fulfilled"?c.value:[];if(!snapshot&&!fallback)return null;const base=snapshot??{indices:[],sectors:[],boards:[],flow:null,global:[],sources:[],fetchedAt:Date.now(),marketDate:fallback?.marketDate??null};const fim=new Map((fallback?.indices??[]).map(x=>[x.code,x]));const fsm=new Map((fallback?.sectors??[]).map(x=>[x.id,x]));const indices=base.indices.map(x=>{const fb=fim.get(x.code);return{...x,price:x.price??fb?.price??null,pct:x.pct??fb?.pct??null,change:x.change??fb?.change??null};});const sectors=base.sectors.map(x=>{const fb=fsm.get(x.id);return{...x,change:x.change??fb?.change??null,available:x.change!=null||fb?.change!=null};});const gb=new Map(globalFallback.map(x=>[x.name,x]));const global=base.global.map(x=>{const fb=gb.get(x.name);return{...x,price:x.price??fb?.price??null,pct:x.pct??fb?.pct??null};});const extra=globalFallback.filter(x=>!global.some(g=>g.name===x.name));return{...base,indices,sectors,global:[...global,...extra],marketDate:base.marketDate||fallback?.marketDate||null} satisfies Snapshot;},component:MarketPage});

type FoldKey="advice"|"valuation"|"money"|"global";
function MarketPage(){const initial=Route.useLoaderData();const storeSnapshot=useApp(s=>s.snapshot);const snapshot=initial??storeSnapshot;const benchPct=snapshot?.indices[0]?.pct??null;const[open,setOpen]=useState<Record<FoldKey,boolean>>({advice:true,valuation:true,money:true,global:true});const toggle=(k:FoldKey)=>setOpen(p=>({...p,[k]:!p[k]}));return <div className="market-page"><FundSectorWatchV2/><FoldSection title="操作建议" subtitle={benchPct==null?"根据最近交易日与自选板块数据生成":`大盘 ${fmtPctShort(benchPct)} · 根据可验证数据生成`} open={open.advice} onToggle={()=>toggle("advice")}><OperationAdvice sectors={snapshot?.sectors||[]} benchPct={benchPct}/></FoldSection>{snapshot?.indices?.length?<IndexGrid indices={snapshot.indices}/>:<EmptyNote>正在读取最近交易日行情…</EmptyNote>}<ExtendedIndexMatrix base={snapshot?.indices||[]}/><MarketHeatmap boards={(snapshot?.boards||[]) as Array<{id:string;name:string;bkCode?:string;change:number|null}>} sectors={(snapshot?.sectors||[]) as Array<{id:string;name:string;bkCode?:string;change:number|null>}/><MacroOverview/><FoldSection title="指数估值红绿灯" subtitle="PE / PB / ROE 与历史估值分位" open={open.valuation} onToggle={()=>toggle("valuation")}><IndexValuationLights/></FoldSection><FoldSection title="资金雷达" subtitle={snapshot?.flow?`主力净流入 ${formatMoney(snapshot.flow.main)} · 资金与行情`:"资金行情"} open={open.money} onToggle={()=>toggle("money")}><MarketPanorama/></FoldSection><FoldSection title="外围市场" subtitle={globalSummary(snapshot?.global)} open={open.global} onToggle={()=>toggle("global")}><div className="rounded-[18px] bg-white/52 p-2 ring-1 ring-white/70"><div className="grid grid-cols-2 gap-2">{(snapshot?.global??[]).map(g=><div key={g.name} className="rounded-2xl bg-bg-elevated p-3"><div className="text-xs text-muted">{g.name}</div><div className="mt-1 text-sm font-semibold tabular-nums text-fg">{g.price==null?"—":g.price.toFixed(g.price>=1000?2:4)}</div><Tone v={g.pct} className="mt-0.5 text-base font-semibold">{g.pct==null?"—":fmtPctShort(g.pct)}</Tone></div>)}</div></div></FoldSection><div className="px-1 pb-2 text-[10px] text-subtle">{snapshot?`市场日期 ${snapshot.marketDate||"最近交易日"} · ${snapshot.sources.map(s=>`${s.name}${s.status==="ok"?"✓":"×"}`).join(" · ")}`:"行情数据连接中"}</div></div>}
function formatMoney(v:number|null|undefined){if(v==null||!Number.isFinite(v))return"—";return`${(v/1e8).toFixed(2)}亿`;}
function globalSummary(g:Snapshot["global"]|undefined){const u=g?.filter(x=>x.price!=null||x.pct!=null)??[];return u.length?`${u.length}/${g?.length??0} 项已更新`:"外围行情连接中";}
function FoldSection({title,subtitle,open,onToggle,children}:{title:string;subtitle:string;open:boolean;onToggle:()=>void;children:ReactNode}){return <section className="mt-3 overflow-hidden rounded-[24px] border border-white/75 bg-white/44 shadow-[0_16px_44px_rgba(38,78,112,.055),inset_0_1px_0_rgba(255,255,255,.95)] backdrop-blur-[22px] saturate-150"><button type="button" onClick={onToggle} className="flex w-full items-center gap-3 px-3.5 py-3 text-left active:bg-white/40" aria-expanded={open}><div className="min-w-0 flex-1"><h2 className="text-[15px] font-semibold tracking-tight text-fg">{title}</h2><div className="mt-0.5 truncate text-[9px] text-subtle">{subtitle}</div></div><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white/72 text-slate-500 shadow-sm ring-1 ring-white/80">{open?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</span></button>{open?<div className="border-t border-white/65 px-2 pb-2">{children}</div>:null}</section>}
